# Generated by Django 6.0.3 on 2026-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
