# Generated by Django 5.2.8 on 2026-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_user_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
