# Generated by Django 5.2.8 on 2026-03-29 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_academic_session_section_optional'),
        ('students', '0007_student_cnic_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, help_text='Which class the student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text='Specific section within the class (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.classsection'),
        ),
    ]
