# Generated by Django 5.2.8 on 2026-03-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_academic_session_section_optional'),
        ('students', '0008_student_class_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport_required',
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=10)),
                ('transport_required', models.BooleanField(default=False)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_section', models.ForeignKey(blank=True, help_text='Section within the class (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.classsection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['-session__start_date'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
