# Generated by Django 5.2.8 on 2026-03-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_reason',
            field=models.CharField(blank=True, choices=[('passout', 'Passed Out'), ('left', 'Left School'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('other', 'Other')], max_length=20),
        ),
    ]
