# Generated by Django 5.2.8 on 2026-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_leaving_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slc_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('submitted', 'Submitted')], default='not_required', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='slc_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
