# Generated by Django 5.2.8 on 2026-03-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('head_teacher', 'Head Teacher'), ('senior_teacher', 'Senior Teacher'), ('junior_teacher', 'Junior Teacher'), ('subject_specialist', 'Subject Specialist'), ('visiting_teacher', 'Visiting Teacher')], default='junior_teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('ba', 'BA'), ('bsc', 'BSc'), ('bed', 'B.Ed'), ('ma', 'MA'), ('msc', 'MSc'), ('med', 'M.Ed'), ('mphil', 'M.Phil'), ('phd', 'PhD'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
