# Generated by Django 5.2.8 on 2026-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_salary_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='house_rent_allowance',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='other_deductions',
        ),
    ]
