# Generated by Django 5.2.8 on 2026-03-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_academic_session_section_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.academicsession'),
        ),
    ]
