# Generated by Django 5.2.8 on 2026-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_session_on_delete_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='name',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
