# Generated by Django 5.2.8 on 2026-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_section_name_default_A'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='school_start_time',
            field=models.TimeField(default='08:00', help_text='School start time for late calculation (default 08:00)'),
        ),
    ]
