# Generated by Django 5.2.8 on 2026-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_school_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='Break / recess end time', null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Break / recess start time', null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='school_end_time',
            field=models.TimeField(blank=True, help_text='School end / closing time', null=True),
        ),
    ]
