# Generated by Django 5.2.8 on 2026-03-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_end_break_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_start_time', models.TimeField(default='08:00', help_text='Default school start time')),
                ('school_end_time', models.TimeField(blank=True, help_text='Default school end time', null=True)),
                ('break_start_time', models.TimeField(blank=True, help_text='Default break start time', null=True)),
                ('break_end_time', models.TimeField(blank=True, help_text='Default break end time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
        migrations.AlterField(
            model_name='classsection',
            name='break_end_time',
            field=models.TimeField(blank=True, help_text='Override break end for this section (leave blank to use school-wide setting)', null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='break_start_time',
            field=models.TimeField(blank=True, help_text='Override break start for this section (leave blank to use school-wide setting)', null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='school_end_time',
            field=models.TimeField(blank=True, help_text='Override end time for this section (leave blank to use school-wide setting)', null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='school_start_time',
            field=models.TimeField(blank=True, help_text='Override start time for this section (leave blank to use school-wide setting)', null=True),
        ),
    ]
