# Generated by Django 5.2.8 on 2026-03-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
