# Generated by Django 5.2.8 on 2026-03-28 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0005_student_cnic_student_guardian_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentFeePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly tuition fee (PKR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly transport fee (0 if not required)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time registration / admission fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('books_fee', models.DecimalField(decimal_places=2, default=0, help_text='Books fee (optional)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, help_text='Exam fee (optional, per term/year)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, help_text='Any special concession or note', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_package', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment Fee Package',
                'verbose_name_plural': 'Enrollment Fee Packages',
            },
        ),
    ]
