# Generated by Django 5.2.8 on 2026-03-29 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_session_on_delete_protect'),
        ('fees', '0002_enrollmentfeepackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentfeepackage',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True = manually overridden for this student; False = auto-filled from class fee structure'),
        ),
        migrations.CreateModel(
            name='FeeRevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_type', models.CharField(choices=[('percentage', 'Percentage %'), ('fixed', 'Fixed Amount +')], max_length=10)),
                ('fee_field', models.CharField(choices=[('tuition_fee', 'Tuition Fee'), ('transport_fee', 'Transport Fee'), ('all_monthly', 'All Monthly Fees'), ('all', 'All Fee Heads')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_to_all', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('affected_count', models.IntegerField(default=0)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(blank=True, related_name='fee_revisions', to='courses.course')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_revisions', to='courses.academicsession')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('books_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fee_structures', to='courses.academicsession')),
            ],
            options={
                'ordering': ['course__name'],
                'unique_together': {('course', 'session')},
            },
        ),
    ]
