# Generated by Django 5.2.8 on 2026-04-02 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_monthlyfeerecord_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfeerecord',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carried-forward unpaid balance from previous months', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
