# Generated by Django 5.2.8 on 2026-04-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_feevoucher_voucherlineitem_voucherpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGenerateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('created', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
