# Generated by Django 6.0.3 on 2026-04-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_autogeneratelog'),
    ]

    operations = [
        # Clear unique_together constraints BEFORE removing their fields
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfeerecord',
            unique_together=None,
        ),
        # Remove FK fields from tables to be deleted
        migrations.RemoveField(model_name='feestructure',    name='course'),
        migrations.RemoveField(model_name='studentfee',      name='fee_structure'),
        migrations.RemoveField(model_name='studentfee',      name='student'),
        migrations.RemoveField(model_name='monthlyfeerecord',name='fee_package'),
        migrations.RemoveField(model_name='monthlyfeerecord',name='generated_by'),
        migrations.RemoveField(model_name='monthlyfeerecord',name='student'),
        migrations.RemoveField(model_name='monthlypayment',  name='monthly_record'),
        migrations.RemoveField(model_name='monthlypayment',  name='received_by'),
        migrations.RemoveField(model_name='payment',         name='received_by'),
        migrations.RemoveField(model_name='payment',         name='student_fee'),
        # Remove amount_paid from EnrollmentFeePackage
        migrations.RemoveField(model_name='enrollmentfeepackage', name='amount_paid'),
        # Delete legacy models
        migrations.DeleteModel(name='EnrollmentPayment'),
        migrations.DeleteModel(name='FeeStructure'),
        migrations.DeleteModel(name='MonthlyFeeRecord'),
        migrations.DeleteModel(name='MonthlyPayment'),
        migrations.DeleteModel(name='Payment'),
        migrations.DeleteModel(name='StudentFee'),
    ]
